### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by icodus** [josh-gaby/2fauth-browser-extension#18] opened 2024-07-26 16:05 UTC
Problem with unlocking. Everything works great after "Add to Chrome" and setup url, token and password. Connects to 2fauth and shows all the accounts there and beautifully generates OTPs. A few logs:
```
192.168.100.100 - - [26/Jul/2024:15:01:26] "GET /api/v1/twofaccounts HTTP/2.0" 200 293
192.168.100.100 - - [26/Jul/2024:15:01:34] "OPTIONS /api/v1/twofaccounts/11/otp HTTP/2.0" 204 0
192.168.100.100 - - [26/Jul/2024:15:01:34] "GET /api/v1/twofaccounts/11/otp HTTP/2.0" 200 92
```
But after closing, the "Verify Identity" doesn't work, saying "Authentication failed". Seems a problem with DNS resolving as it doesn't log to my 2fauth server. No any logs showing that app is trying to connect.

**Comment by josh-gaby** [comment] 2024-07-27 10:38
@icodus The message "Authentication Failed" is shown when you try and unlock the extension using the incorrect password. The extension will not connect to your 2fauth server to unlock, it uses the password you set to derive an encryption key and decrypts your access token using that, it will only attempt to connect to the server once it has successfully decrypted the token.

Before I start digging into this, can you double check that you didn't have caps lock on when you set the password or anything like that?

**Comment by icodus** [comment] 2024-07-28 10:58
I see, thanks for clarification. I'm copying/pasting the same password setting up the extension and trying to unlock. So seems  caps lock should have no influence?

**Comment by josh-gaby** [comment] 2024-07-28 11:09
Ok, I just wanted to rule out simple things before I start looking into it as I haven't come across this issue before.

I will need to try and replicate the issue before I can fix it, can you please answer the following:

Which browser are you having the issue with and which version is it?

What OS are you running?

How did you install the extension, was it through one of the extension stores or did you manually install it?

If you manually installed, which version of the extension did you download?

**Comment by icodus** [comment] 2024-07-28 13:55
Tested on macOS and Windows10. Installed from https://chromewebstore.google.com/search/2fauth on both.
Same 127.0.6 Chrome version, and the same issue, works great after setup but saying "Authentication Failed" on password's unlock.

**Comment by josh-gaby** [comment] 2024-07-28 21:42
I don't have access to a Windows machine for testing but I've been running it on macOS without issue for about a year now without seeing this issue, I'm trying to work this out but I'm not having any luck so far, does your password contain any special characters and if so which ones?

Also, can you try setting it up without a password, confirm it works as expected, then set a simple password like "password" and confirm that it breaks on your systems.

**Comment by icodus** [comment] 2024-07-29 08:28
I've already tested simple passwords with no success and know the passwords are separate.
Just have tried without password. Works great after setup. But after closing and opening again works just fine for a while showing accounts without asking for password but disappears displaying "Invalid  Personal Access Token". 2fauth server logs:
```
192.168.100.100 -- [29/Jul/2024:08:17:58] "GET /api/v1/twofaccounts HTTP/2.0" 401 30 
192.168.100.100 - - [29/Jul/2024:08:17:58] "GET /api/v1/user/preferences HTTP/2.0" 401 30
```
A password, token storing issue, maybe?

**Comment by josh-gaby** [comment] 2024-07-29 08:32
It's starting to sound like your browser is clearing the extensions storage when you close it for some reason.

If you go into your extension manager does the extension report any errors?

**Comment by icodus** [comment] 2024-07-29 08:56
See no errors in chrome://extensions/ nor in 2FAuth extension Details. Should I look somewhere else?
I've got 1Password extension installed on Chrome and it unlocks with the password with no issues.
A conflict with 1Password? Seems unlikely?

**Comment by josh-gaby** [comment] 2024-07-29 08:59
I'm not sure at this stage, I'll install the 1Password extension and try replicating the issue again

**Comment by icodus** [comment] 2024-07-29 09:01
Same "with no password" on Windows and I don't have 1Password there. So seems not 1Password conflict.

**Comment by josh-gaby** [comment] 2024-07-29 09:23
Can you try inspecting the extension and in the console that opens run `await chrome.storage.local.get()` and let me know if anything is output or if it returns undefined?

**Comment by icodus** [comment] 2024-07-29 10:22
The 2fauth extension errors:
```
auth.private.com/api/v1/user/preferences:1     Failed to load resource: the server responded with a status of 401 ()
main.638e253843adf26a.js:1 ERROR TypeError: this.host_pat.substring is not a function
    at e.getStarredPat (main.638e253843adf26a.js:1:403762)
    at new e (main.638e253843adf26a.js:1:403410)
    at qme.#e.ɵfac [as factory] (main.638e253843adf26a.js:1:406551)
    at Hn (main.638e253843adf26a.js:1:36738)
    at jT (main.638e253843adf26a.js:1:77976)
    at wr.create (main.638e253843adf26a.js:1:78151)
    at dh.createComponent (main.638e253843adf26a.js:1:80318)
    at e.activateWith (main.638e253843adf26a.js:1:197954)
    at tq.activateRoutes (main.638e253843adf26a.js:1:204287)
    at main.638e253843adf26a.js:1:203428
handleError @ main.638e253843adf26a.js:1
auth.private.com/api/v1/twofaccounts:1     Failed to load resource: the server responded with a status of 401 ()
main.638e253843adf26a.js:1 ERROR TypeError: this.host_pat.substring is not a function
    at e.getStarredPat (main.638e253843adf26a.js:1:403762)
    at new e (main.638e253843adf26a.js:1:403410)
    at qme.#e.ɵfac [as factory] (main.638e253843adf26a.js:1:406551)
    at Hn (main.638e253843adf26a.js:1:36738)
    at jT (main.638e253843adf26a.js:1:77976)
    at wr.create (main.638e253843adf26a.js:1:78151)
    at dh.createComponent (main.638e253843adf26a.js:1:80318)
    at e.activateWith (main.638e253843adf26a.js:1:197954)
    at tq.activateRoutes (main.638e253843adf26a.js:1:204287)
    at main.638e253843adf26a.js:1:203428
handleError @ main.638e253843adf26a.js:1
main.638e253843adf26a.js:1 ERROR Unauthenticated.
handleError @ main.638e253843adf26a.js:1
```
Local storage seems to work but contains only one item "last-theme:system"

**Comment by josh-gaby** [comment] 2024-07-29 10:39
That setting is stored in a the HTML5 storage location, it can be viewed by running `localStorage` in the extensions console
<img width="304" alt="Screenshot 2024-07-29 at 22 36 55" src="https://github.com/user-attachments/assets/542d0115-51aa-40d1-8921-3672b4b96c6c">

 the one I'm interested in is using the browser storage api which you can check via `await chrome.storage.local.get()`
<img width="897" alt="Screenshot 2024-07-29 at 22 37 51" src="https://github.com/user-attachments/assets/224ab70f-e68e-4952-b661-17f9a4826cdb">

**Comment by icodus** [comment] 2024-07-29 11:06
In what parts of await chrome.storage.local.get() result you're interested in? Would prefer to not disclose domain names and other details in the 2fauth accounts list.

**Comment by josh-gaby** [comment] 2024-07-29 11:08
Not interested in the data at all, just wanting to confirm if there is anything in there when you are on the auth screen seeing the error message

**Comment by icodus** [comment] 2024-07-29 11:17
Sure, too much "pat" lines so most were removed, hope it helps :
{{
```
    "2fauth-app-accounts": [
        {
            "account": "Wiktor Sadowski",
            "algorithm": "sha1",
            "counter": null,
            "digits": 6,
            "group_id": null,
            "icon": "ssask6trlhoSTjvD3YOyx1gWPR97daMrOyu0P7Hr.svg",
            "icon_src": "https://auth.private.com/storage/icons/ssask6trlhoSTjvD3YOyx1gWPR97daMrOyu0P7Hr.svg",
            "id": 4,
            "otp_type": "totp",
            "period": 30,
            "service": "Github"
        }
    ],
    "2fauth-app-preferences": {
        "activeGroup": 0,
        "closeOtpOnCopy": false,
        "copyOtpOnDisplay": false,
        "defaultCaptureMode": "livescan",
        "defaultGroup": 0,
        "displayMode": "list",
        "formatPassword": false,
        "formatPasswordBy": 0.5,
        "getOfficialIcons": true,
        "getOtpOnRequest": true,
        "kickUserAfter": 0,
        "lang": "browser",
        "rememberActiveGroup": true,
        "showAccountsIcons": true,
        "showOtpAsDot": false,
        "theme": "system",
        "useBasicQrcodeReader": false,
        "useDirectCapture": false,
        "useWebauthnOnly": false
    },
    "2fauth-app-settings": {
        "host_pat": [
            237,
            126,
            97,
            ...
            41,
            229
        ],
        "host_url": "https://auth.private.com",
        "lock_timeout": null,
        "password_set": false,
        "theme": "system"
    },
    "2fauth-enc-details": {
        "default": true,
        "iv": [
            5,
            119,
            90,
            60,
            43,
            30,
            8,
            92,
            106,
            207,
            114,
            38
        ],
        "salt": []
    },
    "2fauth-state": {
        "last_active": 1722248016299,
        "loaded": true,
        "lock_type": null,
        "locked": true,
        "pat": [
            237,
            126,
            97,
            ...
            45,
            168,
            41,
            229
        ]
    }
}
```

**Comment by josh-gaby** [comment] 2024-07-29 11:27
Is the 2fauth-enc-details > salt field actually empty or have you cleared that in your post for security?

**Comment by icodus** [comment] 2024-07-29 11:32
Haven't cleared the field. It's from "without password" test.

**Comment by josh-gaby** [comment] 2024-07-29 11:37
Ok, can you do the same thing after setting a password?
Dont need to send the data through, just confirm that 2fauth-enc-details > default is not true and 2fauth-enc-details > salt is not empty

**Comment by icodus** [comment] 2024-07-29 11:54
Set password "password"
2fauth-enc-details > default is false but 2fauth-enc-details > salt **is empty**.
2fauth-enc-key is "password"

**Comment by josh-gaby** [comment] 2024-07-29 12:01
Hmm, okay seems like it could be an issue when encrypting the token, below is what I am seeing when I set the password to "password"
<img width="641" alt="Screenshot 2024-07-29 at 23 57 18" src="https://github.com/user-attachments/assets/723946b7-942c-477f-9779-3b0fd963d5eb">

If I build a new version with some debugging built in would you be open to manually installing a version to help debug the issue?

**Comment by icodus** [comment] 2024-07-29 12:09
Sure, will be happy to test.

**Comment by josh-gaby** [comment] 2024-07-29 14:14
Awesome, attached is a test build of the next version. As well as the debugging stuff, there's also a number of changes/rewrites to the extension so there's a small chance it may actually fix this issue but I doubt it.

After you've installed it but before you start entering your settings, open the console for the extension and run `window.setDebug(true)` to enable the debug output.

I've also exposed the function to reset the extension so you dont need to reinstall to get back to entering your settings when is in the failed state `window.resetExtension()`

Let me know if this build fixes the issue for you but if it doesn't, do all the testing you want, once your done, send me the debug messages from the extensions console, it should help me narrow down where the issue is actually occurring.

[2fauth-2024.7.1-chrome.zip](https://github.com/user-attachments/files/16414583/2fauth-2024.7.1-chrome.zip)

**Comment by icodus** [comment] 2024-07-29 14:49
Didn't work. Great after setup, "Authentication failed" on close/open. Debug:
```
service-worker.js:46 [2FAuth-SW] Got command SET-ENC-KEY
service-worker.js:46 [2FAuth-SW] Setting enc key
service-worker.js:46 [2FAuth-SW]   incoming key length = 8
service-worker.js:46 [2FAuth-SW]   stored key length = 8
service-worker.js:46 [2FAuth-SW]   done (setting enc key)
service-worker.js:46 [2FAuth-SW] Got command ENCRYPT-PAT
service-worker.js:46 [2FAuth-SW] Encrypting PAT
service-worker.js:46 [2FAuth-SW] Deriving encryption key
service-worker.js:46 [2FAuth-SW]   done (deriving encryption key)
service-worker.js:46 [2FAuth-SW]   Regenerating encryption iv...
service-worker.js:46 [2FAuth-SW]   done (regenerating encryption iv)
service-worker.js:46 [2FAuth-SW]   Encrypting...
service-worker.js:46 [2FAuth-SW]   done (encrypting)
service-worker.js:46 [2FAuth-SW] Got command UNLOCK-EXT
service-worker.js:46 [2FAuth-SW] Unlocking extension
service-worker.js:46 [2FAuth-SW] Deriving encryption key
service-worker.js:46 [2FAuth-SW]   done (deriving encryption key)
service-worker.js:46 [2FAuth-SW] Decrypting PAT
service-worker.js:46 [2FAuth-SW]   done (decrypting pat)
service-worker.js:46 [2FAuth-SW]   done (unlocking extension)
service-worker.js:46 [2FAuth-SW] Got command CHECK-LOCKED
service-worker.js:46 [2FAuth-SW] Got command SET-ENC-KEY
service-worker.js:46 [2FAuth-SW] Setting enc key
service-worker.js:46 [2FAuth-SW]   incoming key length = 8
service-worker.js:46 [2FAuth-SW]   stored key length = 8
service-worker.js:46 [2FAuth-SW]   done (setting enc key)
service-worker.js:46 [2FAuth-SW] Got command UNLOCK-EXT
service-worker.js:46 [2FAuth-SW] Unlocking extension
service-worker.js:46 [2FAuth-SW] Deriving encryption key
service-worker.js:46 [2FAuth-SW]   done (deriving encryption key)
service-worker.js:46 [2FAuth-SW] Decrypting PAT
service-worker.js:46 [2FAuth-SW]   failed (unlocking extension) - decryption error
```

**Comment by icodus** [comment] 2024-07-29 14:57
2fauth-enc-details > salt is empty

**Comment by josh-gaby** [comment] 2024-07-29 15:08
Thanks for that, gives me a lot more info to go off. I will try and upload another debug build tomorrow night if you don't mind trying again.

**Comment by icodus** [comment] 2024-07-29 15:09
Will try for sure.

**Comment by josh-gaby** [comment] 2024-07-30 06:57
I haven't had time to get anywhere on this today, been busy at the day job.
I will let you know when I get a new debug version ready for testing.

**Comment by josh-gaby** [comment] 2024-08-02 22:35
@icodus I'm still working on this, been super busy with work so havent been able to get a new debug version ready yet.

Would you be able to try installing the extension in Firefox and checking if it has the same issue for you there? Might help narrow it down if we can confirm whether its isolated to Chrome or if its happening in both browsers.

**Comment by icodus** [comment] 2024-08-07 10:33
Same issue on Firefox. Installed from https://addons.mozilla.org/en-US/firefox/addon/2fauth/
May I ask how you are testing the extension so I can try it myself?

**Comment by josh-gaby** [comment] 2024-08-07 10:47
I don't have any automated tests yet, currently I'm just installing the extension in the browser and manually testing.
I've been doing that with both Chrome and Firefox on Linux and macOS, no access to a Window machine at the moment.

Interestingly, the Chrome webstore reports that 75% of people using the extension are also running Windows, makes me wonder if its possibly something in your environment?
![image](https://github.com/user-attachments/assets/915d55bd-311b-416d-b4f6-59e759bd0a43)

I'm really struggling to figure out whats going on here since I can't replicate the issue, I'll keep trying though.

**Comment by icodus** [comment] 2024-08-11 16:55
Just to saying that your extension from 2fauth-2024.7.1-chrome.zip works great on Windows 10! And it's really impressive with account and appearance settings. "About" looks very nice too :-) Congrats!

**Comment by josh-gaby** [comment] 2024-08-11 20:43
Great to hear its finally working for you, did anything in your environment change before it started working or did you just reinstall it again?

**Comment by icodus** [comment] 2024-08-12 15:52
On Windows I just tried your newest Chrome version from dev 2fauth-2024.7.1-chrome.zip and it worked perfectly the first time ( the previous one didn't ). Then I removed that dev release and installed the "regular" one from https://chromewebstore.google.com/detail/2fauth/oplibojgambbikkdocijojhbdgdgealg and it works great too.

**Comment by icodus** [comment] 2024-08-12 22:45
Strange indeed. I wouldn't have seen "Authentication failed" if it had worked the first time, right? A cache somewhere?
Firefox extension still doesn't work.

**Comment by icodus** [comment] 2024-08-12 22:59
Just reinstalled the "regular" one macOS and it works there too. A bit broken downloads/installations on Windows and Mac most probably. An issue with internet connection maybe. Sorry for the confusion.

**Comment by josh-gaby** [comment] 2024-08-13 04:24
Ok, I'm going to close this issue for now, feel free to reopen if it happens again.

**Closed by josh-gaby** 2024-08-13 04:24 UTC
